name: Android NDK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up NDK r16b
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
        unzip android-ndk-r16b-linux-x86_64.zip
    - name: Build .so files
      run: |
        cd android-ndk-r16b
        ./ndk-build -C $GITHUB_WORKSPACE/jni
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libs
        path: $GITHUB_WORKSPACE/libs/
